Fatal error: exception Failure("Found return statement in unexpected place (i.e. a statement outside of a function.")
